import React, { useState } from 'react';
import { MenuIcon, DownloadIcon, ShareIcon, TrashIcon, PlusCircleIcon, XIcon } from '../icons/Icons';

interface PlaceholderProps {
  toggleSidebar: () => void;
}

const mockReports = [
    { id: 1, name: 'Q3 2024 User Activity', date: '2024-10-01', by: 'Jane Doe', format: 'PDF' },
    { id: 2, name: 'Monthly Login Summary - Sep', date: '2024-09-30', by: 'System', format: 'CSV' },
    { id: 3, name: 'Project Phoenix Task Completion', date: '2024-09-28', by: 'Alex Johnson', format: 'PDF' },
    { id: 4, name: 'Weekly Signup Breakdown', date: '2024-09-25', by: 'System', format: 'CSV' },
    { id: 5, name: 'Annual Performance Review', date: '2024-09-15', by: 'Jane Doe', format: 'PDF' },
];

const ReportsPlaceholder: React.FC<PlaceholderProps> = ({ toggleSidebar }) => {
  const [activeTab, setActiveTab] = useState('Generated');
  const [isModalOpen, setModalOpen] = useState(false);

  const handleActionClick = (action: string, reportName: string) => {
    alert(`${action} report: "${reportName}"`);
  };

  const handleGenerateReport = (event: React.FormEvent) => {
    event.preventDefault();
    alert('Generating new report...');
    setModalOpen(false);
  };

  return (
    <div className="container mx-auto">
      <header className="mb-8">
        <div className="flex flex-col md:flex-row items-center justify-between">
            <div className="flex items-center">
                <button onClick={toggleSidebar} className="md:hidden mr-4 p-2 rounded-md hover:bg-gray-200">
                    <MenuIcon className="w-6 h-6 text-gray-600" />
                </button>
                <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">Reports</h1>
            </div>
            <button 
                onClick={() => setModalOpen(true)}
                className="flex items-center space-x-2 px-4 py-2 mt-4 md:mt-0 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition shadow-sm"
            >
                <PlusCircleIcon className="w-5 h-5" />
                <span className="text-sm font-medium">Generate New Report</span>
            </button>
        </div>
      </header>

      <div className="bg-white rounded-lg shadow-md p-4 sm:p-6">
        <div className="border-b border-gray-200 mb-4">
            <nav className="-mb-px flex space-x-6" aria-label="Tabs">
                {['Generated', 'Scheduled', 'Templates'].map(tab => (
                    <button
                        key={tab}
                        onClick={() => setActiveTab(tab)}
                        className={`py-3 px-1 border-b-2 text-sm font-medium ${
                            activeTab === tab 
                                ? 'border-blue-500 text-blue-600' 
                                : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                        }`}
                    >
                        {tab}
                    </button>
                ))}
            </nav>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report Name</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date Generated</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Format</th>
                <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {mockReports.map((report) => (
                <tr key={report.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{report.name}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{report.date}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{report.by}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm">
                    <span className={`px-2 py-1 text-xs font-semibold rounded-full ${ report.format === 'PDF' ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'}`}>{report.format}</span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <div className="flex items-center justify-end space-x-3">
                        <button onClick={() => handleActionClick('Downloading', report.name)} className="text-blue-600 hover:text-blue-900"><DownloadIcon className="w-5 h-5"/></button>
                        <button onClick={() => handleActionClick('Sharing', report.name)} className="text-gray-500 hover:text-gray-800"><ShareIcon className="w-5 h-5"/></button>
                        <button onClick={() => handleActionClick('Deleting', report.name)} className="text-red-600 hover:text-red-900"><TrashIcon className="w-5 h-5"/></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      
      {isModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-40 flex items-center justify-center" aria-modal="true" role="dialog">
            <div className="bg-white rounded-lg shadow-xl p-6 w-full max-w-md m-4">
                <div className="flex items-center justify-between mb-4">
                    <h2 className="text-xl font-bold text-gray-800">Generate Report</h2>
                    <button onClick={() => setModalOpen(false)}><XIcon className="w-6 h-6 text-gray-500 hover:text-gray-800" /></button>
                </div>
                <form onSubmit={handleGenerateReport}>
                    <div className="space-y-4">
                        <div>
                            <label htmlFor="reportName" className="block text-sm font-medium text-gray-700">Report Name</label>
                            <input type="text" id="reportName" defaultValue="New Custom Report" className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500" required />
                        </div>
                        <div>
                            <label htmlFor="reportType" className="block text-sm font-medium text-gray-700">Report Type</label>
                            <select id="reportType" className="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500">
                                <option>User Activity</option>
                                <option>Login Summary</option>
                                <option>Project Completion</option>
                            </select>
                        </div>
                        <div className="flex justify-end space-x-3 pt-4">
                            <button type="button" onClick={() => setModalOpen(false)} className="px-4 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300">Cancel</button>
                            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">Generate</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
      )}
    </div>
  );
};

export default ReportsPlaceholder;